# Generated by Django 4.1.6 on 2023-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '地区前缀', 'verbose_name_plural': '地区前缀'},
        ),
        migrations.AddField(
            model_name='area',
            name='area_city',
            field=models.CharField(default=0, max_length=10, verbose_name='城市'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=10, verbose_name='省份'),
        ),
    ]
