# Generated by Django 4.1.6 on 2023-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_area_options_area_area_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(db_column='area_name', max_length=10, verbose_name='省份'),
        ),
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='area_pro',
        ),
    ]
