# Generated by Django 4.1.6 on 2023-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0003_alter_iptable_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptable',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='IP'),
        ),
    ]
