# Generated by Django 4.1.6 on 2023-02-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_level_group_type'),
        ('iptables', '0004_alter_iptable_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptable',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='phone_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.level', verbose_name='黑名单组'),
        ),
    ]
