# Generated by Django 4.1.6 on 2023-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, '12321'), (1, '自定义组1'), (2, '自定义组2')], verbose_name='级别')),
                ('phone', models.CharField(max_length=11, verbose_name='号码')),
            ],
            options={
                'verbose_name': 'Black Phone',
                'verbose_name_plural': 'Black Phones',
            },
        ),
    ]
