# Generated by Django 4.1.6 on 2023-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': '自定义组'},
        ),
        migrations.AddField(
            model_name='level',
            name='group_type',
            field=models.BooleanField(default=0, verbose_name='群组类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=12, verbose_name='自定义组名'),
        ),
    ]
