# Generated by Django 4.1.6 on 2023-02-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_level_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='group_type',
            field=models.CharField(choices=[('黑名单', '黑名单'), ('白名单', '白名单')], max_length=8, verbose_name='群组类型'),
        ),
    ]
