# Generated by Django 4.1.6 on 2023-02-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_level_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackphone',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.level'),
        ),
    ]
