# Generated by Django 4.1.6 on 2023-02-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_alter_blackphone_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlackPhone',
            new_name='Phone',
        ),
        migrations.DeleteModel(
            name='WhitePhone',
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': '电话号码', 'verbose_name_plural': '电话号码'},
        ),
    ]
