# Generated by Django 4.1.6 on 2023-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0006_remove_rule_phone_group_remove_rule_priority'),
        ('lists', '0009_rename_blackphone_phone_delete_whitephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='号码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '黑名单列表',
            },
        ),
        migrations.RemoveField(
            model_name='phone',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
