# Generated by Django 4.1.6 on 2023-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_blacklist_remove_phone_level_delete_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='号码'),
        ),
    ]
