# Generated by Django 4.1.6 on 2023-02-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(max_length=8, verbose_name='请求类型')),
                ('call_Id', models.IntegerField(verbose_name='呼叫ID')),
                ('caller', models.CharField(max_length=20, verbose_name='主叫号码')),
                ('callee', models.CharField(max_length=20, verbose_name='被叫号码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
