# Generated by Django 4.1.6 on 2023-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='call_type',
            field=models.CharField(max_length=20, verbose_name='请求类型'),
        ),
    ]
