# Generated by Django 4.1.6 on 2023-02-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_call_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': '请求记录', 'verbose_name_plural': '请求记录'},
        ),
    ]
