# Generated by Django 4.1.6 on 2023-02-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_log_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='area_city',
            field=models.CharField(default='北京', max_length=10, verbose_name='城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='area_pro',
            field=models.CharField(default='北京', max_length=10, verbose_name='省份'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='blackornot',
            field=models.BooleanField(default=False, verbose_name='是否黑名单'),
        ),
    ]
